from fpdf import FPDF
from datetime import datetime
import os

class NTAVReport(FPDF):
    def header(self):
        # NTAV 브랜드 헤더
        self.set_fill_color(10, 10, 20) # 다크 블루 배경
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('helvetica', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, 'NTAV SECULAB V2.0', ln=True, align='L')
        
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 0, 'Never Trust, Always Verify - Deep Scan Security Report', ln=True, align='L')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by NTAV AI Engine | {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', align='C')

def generate_scan_report(scan_data: dict) -> str:
    """
    분석 데이터를 기반으로 고품격 PDF 리포트를 생성하고 파일 경로를 반환합니다.
    """
    pdf = NTAVReport()
    pdf.add_page()
    
    # 리포트 요약 섹션
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(30, 30, 60)
    pdf.cell(0, 10, '1. Executive Summary', ln=True)
    pdf.ln(5)
    
    pdf.set_font('helvetica', '', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 8, f"Scan Type: {scan_data.get('type', 'Unknown').upper()}")
    pdf.multi_cell(0, 8, f"Security Score: {scan_data.get('score', 0)} / 100")
    pdf.ln(5)
    
    # AI 코멘트 (강조)
    pdf.set_fill_color(240, 245, 255)
    pdf.set_font('helvetica', 'I', 11)
    pdf.multi_cell(0, 10, f"NTAV AI Verdict: \"{scan_data.get('ntav_comment', 'No comment available.')}\"", border=1, fill=True)
    pdf.ln(10)
    
    # 상세 점검 내역 트리
    pdf.set_font('helvetica', 'B', 16)
    pdf.cell(0, 10, '2. Detailed Audit Results', ln=True)
    pdf.ln(5)
    
    results = scan_data.get('results', [])
    for item in results:
        # 결과에 따른 색상 정의
        if item.get('result') == 'Pass':
            pdf.set_text_color(0, 150, 0) # Green for Pass
        else:
            pdf.set_text_color(200, 0, 0) # Red for Fail
            
        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 8, f"[{item.get('result', 'N/A')}] {item.get('title', 'Untitled Check')}", ln=True)
        
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 6, f"Description: {item.get('desc', 'No description.')}")
        pdf.multi_cell(0, 6, f"Impact: {item.get('impact', 'Normal')}")
        pdf.ln(4)
    
    # 임시 디렉토리에 저장
    report_filename = f"NTAV_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    report_path = os.path.join("/tmp", report_filename)
    pdf.output(report_path)
    
    return report_path
